server:
  port: 8082

rest:
  client:
    alert-rest-client:
      url: https://api.opsgenie.com/v2/alerts
      auth-request-id: GenieKey ${GENIE_KEY}
      team-id: ${TEAM_ID}
#      auth-request-id: ${GENIE_KEY}
#      team-id: 94950924-6be6-4ccb-ac88-1c3232ed1d3d

spring:
  kafka:
    consumer:
      group-id: default

topic:
  name: frames
